edited workflow and added test cases

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,50 +2,50 @@ name: CI/CD Pipeline
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 jobs:
   build-test:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v4
-      with:
-        python-version: "3.10.12"
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.10.12"
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-        pip install pytest
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          pip install pytest
 
-    - name: Run Tests
-      run: pytest || echo "⚠️ No tests found, skipping"
+      - name: Run Tests
+        run: pytest || echo "⚠️ No tests found, skipping"
 
   docker-build:
     runs-on: ubuntu-latest
     needs: build-test
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Build Docker image (local validation)
-      run: docker build -t fitness-app .
+      - name: Build Docker image (local validation)
+        run: docker build -t fitness-app .
 
   deploy-ec2:
     runs-on: ubuntu-latest
     needs: docker-build
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
     - name: Deploy to EC2 via SSH
       uses: appleboy/ssh-action@v0.1.10
@@ -58,26 +58,26 @@ jobs:
           mkdir -p ~/app
           cd ~/app
 
-          # Clone repo if not exists
-          if [ ! -d "devops-ci-cd" ]; then
-            git clone https://github.com/surya0210/devops-ci-cd.git
-          fi
+            # Clone repo if not exists
+            if [ ! -d "devops-ci-cd" ]; then
+              git clone https://github.com/surya0210/devops-ci-cd.git
+            fi
 
-          cd devops-ci-cd
+            cd devops-ci-cd
 
-          # Allow git safe directory
-          git config --global --add safe.directory /home/ubuntu/app/devops-ci-cd
+            # Allow git safe directory
+            git config --global --add safe.directory /home/ubuntu/app/devops-ci-cd
 
-          # Pull latest changes
-          git pull origin main
+            # Pull latest changes
+            git pull origin main
 
-          # Stop & remove old container
-          sudo docker stop fitness-app || true
-          sudo docker rm fitness-app || true
+            # Stop & remove old container
+            sudo docker stop fitness-app || true
+            sudo docker rm fitness-app || true
 
-          # Optional: clean up dangling images
-          sudo docker system prune -af || true
+            # Optional: clean up dangling images
+            sudo docker system prune -af || true
 
-          # Build new image & run
-          sudo docker build -t fitness-app .
-          sudo docker run -d -p 5001:5001 --name fitness-app fitness-app
+            # Build new image & run
+            sudo docker build -t fitness-app .
+            sudo docker run -d -p 5001:5001 --name fitness-app fitness-app
